FROM node:22-alpine AS base
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile=false
RUN pnpm --filter @paas/database prisma:generate
RUN pnpm --filter @paas/api build
CMD ["node","apps/api/dist/server.js"]
